version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.lucene:lucene-facet
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
  - dependency-name: org.apache.lucene:lucene-analyzers-common
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
  - dependency-name: org.apache.lucene:lucene-queryparser
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
  - dependency-name: org.apache.lucene:lucene-core
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
